### ISSUE TITLE
503

### ISSUE THREAD

**Issue by zackshapiro** [RF-Nelson/splish#1]
Hey Rich,

I'm checking out your code right now, running it locally and getting a 503. I'd love to see the good work you did, mind fixing this and I'll take a look? 

Thanks!
Shap

**Comment by RF-Nelson** [comment]
I think I've sorted that out. If you re-pull you should be able to run the rails server locally and visit the page without a problem. It's also now running as it should on Heroku: http://splishthat.herokuapp.com/

This specific error was caused whenever a user wasn't signed in and went to the page. While adding a new feature, I accidentally deleted line #15 of the header layout, which starts a Rails if-else relying on whether a user is signed in or not. I never noticed this while developing because I was always signed in, so on line #16 when Rails interpolates the `current_user`'s `id`, this was never an issue. But if I had signed out, and tried to access that page I would have received the 503 error since there is no `current_user` until the user signs into an account. I neglected to run my rspec tests, which would have picked this up in the user auth unit test.
